---
title: "Past R Events Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    includes:
      after_body: "../../fragments/afterInit.html"
    css: ["../../fragments/custom.css", "css/custom.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(countrycode)
library(reactable)
library(htmltools)
library(lubridate)
options(DT.options = list(scrollY="250px",scrollX="50px", pageLength = 10, autoWidth = TRUE))
library(echarts4r)
source("past_events.R")
```

Sidebar {.sidebar data-width=200}
=====================================

```{r, echo=FALSE, results='asis'}
sidebar <- htmltools::includeHTML('../../fragments/sidebar.html')

cat(stringr::str_replace_all(sidebar, '\\./', "./../"))
```


Past R Events
=====================================

Row
-------------------------------------

### Total Events

```{r}

valueBox(total_events, icon = "fa-calendar", color = "#435f9c")

```

### Total Attendees

```{r}

valueBox(total_rsvp, icon = "fa-users", color = "#0586c4")

```

### Events - Cities

```{r}
valueBox(total_cities, icon = "fa-building", color = "#435f9c")
```

### Events - Countries

```{r}
valueBox(total_countries, icon = "fa-globe", color = "#0586c4")
```

Row {data-height=600}
-----------------------------------------------------------------------

### Global R Events Distribution
```{r}
eventcountry %>% e_country_names(group_country) %>% # helper
  e_charts(group_country) %>%
  e_map(values) %>%
  e_visual_map(min =0, max = max(eventcountry$values), color = c("#ba160c","#ce5b54","#bf716c", "#e89993","#f0b5b0","#f2c5c1","#f0d9d7")) %>% e_tooltip() %>%
  e_title("Global Distribution of Past R Meetup Events", "All-Time")
```

Row {data-height=400}
-----------------------------------------------------------------------

### Count of R events <small> per Year </small>

```{r}
mycolor <- c("#435f9c","#003636","#a9a9a9", "#91c8c8")
rownames(event_group_year) <- event_group_year$round_year
event_group_year %>% 
  mutate(
    Year = row.names(.)
  ) %>%
  e_charts(Year) %>%
  e_bar(serie = Events_Count) %>% 
  e_title(text = "Events Yearly Statistics", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Attendance in R Events <small> per Year </small>

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

rownames(event_group_rsvp_year) <- event_group_rsvp_year$round_year
event_group_rsvp_year %>% 
  mutate(
    Year = row.names(.)
  ) %>%
  e_charts(Year) %>%
  e_bar(serie = Attendees) %>% 
  e_title(text = "Yearly Attendance", 
          subtext = "RSVP Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Count of R events <small> per Month </small>

```{r}
mycolor <- c("#fc5185","#003636","#a9a9a9", "#91c8c8")

months.df %>% 
  e_charts(month) %>%
  e_area(Events_Count) %>% 
  e_title(text = "Events Monthly Statistics", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Attendance in R Events <small> per Month </small>

```{r}
mycolor <- c("#fc5185","#003636","#a9a9a9", "#91c8c8")

months.rsvpdf %>% 
  e_charts(month) %>%
  e_area(Attendees) %>% 
  e_title(text = "Monthly Attendance", 
          subtext = "RSVP Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=500}
-----------------------------------------------------------------------

### R Events Distribution - Region Wise <small> Across Globe </small>

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

region_df %>% 
  arrange(desc(Events_Count)) %>%
  e_charts(group_region) %>%
  e_bar(serie = Events_Count) %>% 
  e_title(text = "Events Across Regions", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Attendance in R Events - Region Wise

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

region_df_rsvp %>% 
  arrange(desc(Attendees)) %>%
  e_charts(group_region) %>%
  e_bar(serie = Attendees) %>% 
  e_title(text = "Region Wise Attendance", 
          subtext = "RSVP Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=800}
-----------------------------------------------------------------------

### Top 40 City destinations for R events

```{r}
top_dest_city <- top_dest_city %>%
  arrange(Events_freq)

mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")
top_dest_city %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title("Top Cities for R Events", "City") %>% 
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>% 
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Timeline for Cumulative Growth of R events

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")
cumm_event_count %>%
  e_charts(Event_date) %>%
  e_area(csum, name = "Cumulative Event Count", legend = FALSE) %>%
  e_datazoom(type = "slider") %>%
  e_zoom(dataZoomIndex = 0,
         start = 0,
         end = 100) %>% 
  e_title(text = "Growth of R Events Across Years", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=1000}
-----------------------------------------------------------------------

### Top Destinations for R events | <small> Event count per city per region </small>

```{r}
mycolor <- c("#435f9c","#003636","#a9a9a9", "#91c8c8")
plot1 <- tail(df1, 10) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Africa Region", 
          subtext = "Top 10 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot2 <- tail(df2, 20) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Latin America Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot3 <- tail(df3, 20) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Asia Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot4 <- tail(df4, 10) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Australia Region", 
          subtext = "Top 10 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot5 <- tail(df5, 20) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "US/Canada Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot6 <- tail(df6, 20) %>%
  e_charts(x = group_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Europe Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

e_arrange(plot5, plot6, plot3, plot2, plot1, plot4, rows = 3, cols = 3)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Top Destinations for R Events | <small> Users per Country

```{r}
mycolor <- c("#435f9c","#003636","#a9a9a9", "#91c8c8")

top_dest_country %>% 
  arrange(desc(Attendees)) %>%
  e_charts(venue_country_name) %>%
  e_bar(serie = Attendees) %>% 
  e_title(text = "Top R Event Destinations", 
          subtext = "Attendees Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Top R Events Destinations | <small> Events per Country </small> 

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

events_by_country %>% 
  arrange(desc(Events_Frequency)) %>%
  e_charts(venue_country_name) %>%
  e_bar(serie = Events_Frequency) %>% 
  e_title(text = "Top R Events Organizing Countries", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=500}
-----------------------------------------------------------------------

### Data Table

```{r}
display_df %>% 
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    #defaultSorted = "Date",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Event_name = colDef(
        name = "Event Name",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE,
        html = TRUE,
        cell = function(value, index) {
          sprintf('<a href="%s" target="_blank">%s</a>', display_df$Link[index], value)
        }
      ),
      Link = colDef(
        show = FALSE
      ),
      City = colDef(
        filterable = TRUE
      ),
      Country = colDef(
        filterable = TRUE
      ),
      RSVP_count = colDef(
        name = "Attendees Count",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(display_df$RSVP_count), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )
    ),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```
