---
title: "Upcoming R Events Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    includes:
      after_body: ["../../fragments/footer.html", "../../fragments/afterInit.html"]
    css: ["../../fragments/custom.css", "css/custom.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(countrycode)
options(DT.options = list(scrollY="300px",scrollX="50px", pageLength = 10, autoWidth = TRUE))
library(echarts4r)
library(leaflet)
library(sp)
library(V8)
library(reactable)
library(htmltools)
library(geojsonio)
source("upcoming_events.R")
```

Sidebar {.sidebar data-width=200}
=====================================

```{r, echo=FALSE, results='asis'}
sidebar <- htmltools::includeHTML('../../fragments/sidebar.html')

cat(stringr::str_replace_all(sidebar, '\\./', "./../"))
```


Upcoming R Events
=====================================

Row
-------------------------------------

### Upcoming Events

```{r}

valueBox(total_events, icon = "fa-calendar", color = "#435f9c")

```

### Registered Attendees - Till Now

```{r}

valueBox(total_rsvp, icon = "fa-users", color = "#0586c4")

```

### Events - Cities

```{r}
valueBox(total_cities, icon = "fa-building", color = "#435f9c")
```

### Events - Countries

```{r}
valueBox(total_countries, icon = "fa-globe", color = "#0586c4")
```

Row {data-height=800}
-------------------------------------

### Mapping of Upcoming Events | <small> Worlwide </small>

```{r}
srcURL <- "https://cdn.rawgit.com/turban/Leaflet.Graticule/master/examples/lib/countries-110m.js"
v8 <- V8::v8()
v8$source(srcURL)

geoJSON <- geojsonio::as.json(v8$get("countries"))
spdf <- geojsonio::geojson_sp(geoJSON)

crs_wintri <- "+proj=wintri +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +datum=WGS84 +no_defs +over"

leaflet(upcoming_event, 
        elementId = "rugs-map",
        options =
          leafletOptions(minZoom = 1.5,maxZoom = 6,
                         crs = leafletCRS(crsClass = "L.Proj.CRS",
                                          code = "EPSG:2163",
                                          proj4def = "+proj=laea +lat_0=0 +lon_0=0 +lat_ts=300 +x_0=0 +y_0=0 +a=6370000 +b=6370000 +units=m +no_defs",
                                          resolutions = c(131072,65536, 32768, 16384, 8192, 4096, 2048)
                                          
                         )))%>%
  addGraticule(style = list(color = "#727171", weight = 1.5, opacity = 0.5)) %>%
  addPolygons(data = spdf, weight = 1.2, color = "#2165b6")  %>% 
  addMarkers(popup = ~paste0('<a href =',link,'>', name, '</a><br> Event Date & Time: ', time, 
                             '<br> Country:', venue_country_name, '<br>',
                             '<br> Organizing Group: ',group_name,
                             '<br> RSVP Count: ',yes_rsvp_count, '<br> Venue: ', venue_name
  ),
  clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = FALSE)
  ) %>% setView(10,10,1.5)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Upcoming R Events | <small> Country Wise

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

events_by_country %>% 
  arrange(desc(Events_frequency)) %>%
  e_charts(venue_country_name) %>%
  e_bar(serie = Events_frequency) %>% 
  e_title(text = "Events Distribution", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Upcoming R Events | <small> Region Wise </small>

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

region_df %>% 
  arrange(desc(Events_frequency)) %>%
  e_charts(group_region) %>%
  e_bar(serie = Events_frequency) %>% 
  e_title(text = "R Events Frequencies Region Wise", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=590}
-----------------------------------------------------------------------

### Top R events by attendance

```{r}
top_events %>% 
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      name = colDef(
        name = "Event Name",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE,
        html = TRUE,
        cell = function(value, index) {
          sprintf('<a href="%s" target="_blank">%s</a>', top_events$link[index], value)
        }
      ),
      link = colDef(
        show = FALSE
      ),
      Attendees = colDef(
        name = "Attendees Count",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(top_events$Attendees), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )
    ),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```

### Types of Events 

```{r}
mycolor <- c("#0586c4","#003636","#a9a9a9", "#91c8c8")

event_type %>% 
  arrange(desc(Count)) %>%
  e_charts(EventType) %>%
  e_bar(serie = Count) %>% 
  e_title(text = "Online Vs In-Person Events", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=550}
-----------------------------------------------------------------------

### Data-table

```{r}
display_df %>% 
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Event_name = colDef(
        name = "Event Name",
        width = 200,
        defaultSortOrder = "desc",
        filterable = TRUE,
        html = TRUE,
        cell = function(value, index) {
          sprintf('<a href="%s" target="_blank">%s</a>', display_df$Link[index], value)
        }
      ),
      Link = colDef(
        show = FALSE
      ),
      Venue_Name = colDef(
        filterable = TRUE,
        name = "Venue"
      ),
      Country = colDef(
        filterable = TRUE
      ),
      RSVP_count = colDef(
        name = "Attendees Count",
        defaultSortOrder = "desc",
        cell = function(value) {
          width <- paste0(value * 100 / max(display_df$RSVP_count), "%")
          value <- format(value, big.mark = ",")
          value <- format(value, width = 9, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "6px"),
            div(class = "bar", style = list(width = width, backgroundColor = "#fc5185"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )
    ),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```