---
title: "R Community Explorer | #rstats"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    includes:
      in_header: "../fragments/ganalytics.html"
      after_body: ["../fragments/footer.html", "../fragments/afterInit.html"]
    css: ["../fragments/custom.css", "css/custom.css"]
---

```{r libs, include=FALSE}
library(flexdashboard)
library(rtweet)
library(dplyr)
library(vroom)
library(purrr)
library(stringr)
library(tidytext)
library(lubridate)
library(echarts4r)

source("global.R")

data_file_url <- "https://github.com/r-community/twitterdata/raw/main/data/full_data.csv.gz"

try(Sys.setlocale("LC_TIME", "C"), silent = TRUE)

rstats_tweets <-
  readData(data_file_url) %>%
  filter(str_detect(user_id, "^\\d")) %>%
  filter(floor_date(created_at, "month") != as_date("2020-05-01"))
```


```{r setup, include=FALSE, cache=TRUE}

tweets_timeline <- rstats_tweets %>% 
  ts_data(by = "months") %>% 
  filter(time != as_datetime("2020-05-08"))

tweets_by_day <- rstats_tweets %>% 
  ts_data(by = "days") %>%
  filter(time != as_datetime("2020-05-08")) %>% 
  mutate(weekday = wday(time, label = TRUE, abbr = TRUE),
         myear = format(time, format = "%b %Y"),
         week = format(time, format = "%U")) %>% 
  rename(tweets = n)

likes_timeline <- rstats_tweets %>% 
  select(created_at, favorite_count) %>% 
  group_by(floor_date(created_at, "month")) %>% 
  summarise(n = sum(favorite_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  setNames(c("time", "n")) %>% 
  filter(!is.na(time))

likes_by_day <- rstats_tweets %>% 
  select(created_at, favorite_count) %>% 
  group_by(floor_date(created_at, "day")) %>% 
  summarise(n = sum(favorite_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  setNames(c("time", "likes")) %>% 
  filter(!is.na(time))

replies_by_day <- rstats_tweets %>% 
  select(created_at, reply_count) %>% 
  group_by(floor_date(created_at, "day")) %>% 
  summarise(n = sum(reply_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  setNames(c("time", "replies")) %>% 
  filter(!is.na(time))

n_tweets <- rstats_tweets %>% 
  pull(status_id) %>% 
  unique() %>% 
  length()

n_likes <- rstats_tweets %>% 
  pull(favorite_count) %>% 
  sum(., na.rm = TRUE)

retweets_timeline <- rstats_tweets %>% 
  select(created_at, retweet_count) %>% 
  group_by(floor_date(created_at, "month")) %>% 
  summarise(n = sum(retweet_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  setNames(c("time", "n")) %>% 
  filter(!is.na(time))

retweets_by_day <- rstats_tweets %>% 
  select(created_at, retweet_count) %>% 
  group_by(floor_date(created_at, "day")) %>% 
  summarise(n = sum(retweet_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  setNames(c("time", "retweets")) %>% 
  filter(!is.na(time))

n_retweets <- rstats_tweets %>% 
  pull(retweet_count) %>% 
  sum(., na.rm = TRUE)

n_users <- rstats_tweets %>% 
  pull(user_id) %>% 
  unique() %>% 
  length()

active_users <- rstats_tweets %>%
  count(user_id, screen_name) %>%
  slice_max(n, n = 25, with_ties = FALSE) %>%
  mutate(
    profile_url = str_glue("https://twitter.com/{screen_name}"),
    screen_name = str_glue('<a href="{profile_url}" target="_blank">@{screen_name}</a>'),
    n_tweets = formattable::color_bar("#a3c1e0", formattable::proportion)(n)
  ) %>%
  select(screen_name, n_tweets)

mycolor <- c("#2780e3", "#003636", "#a9a9a9", "#91c8c8")

top_tweets <- rstats_tweets %>%
  mutate(popularity = favorite_count + (retweet_count * 2)) %>% 
  slice_max(popularity, n = 10)

by_day_metrics <- tweets_by_day %>% 
  left_join(retweets_by_day, by = "time") %>% 
  left_join(likes_by_day, by = "time") %>% 
  left_join(replies_by_day, by = "time") %>% 
  tidyr::replace_na(replace = list(likes = 0, retweets = 0))
```

```{r text_proc, include=FALSE, cache=TRUE}
top_words <- rstats_tweets %>% 
  unnest_tweets(word, text) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE) %>%
  filter(!str_starts(word, "#|@|http")) %>% 
  slice_max(n, n = 500)

top_hashtags <- rstats_tweets %>%
  tidyr::separate_rows(hashtags, sep = " ") %>%
  count(hashtags) %>%
  filter(!(hashtags %in% c("rstats", "RStats"))) %>%
  slice_max(n, n = 50, with_ties = FALSE)

emoji_regex <- "[\\uD83C-\\uDBFF\\uDC00-\\uDFFF\u2600-\u27ff]+"
top_emojis <- rstats_tweets %>% 
  unnest_tweets(text, text) %>% 
  filter(str_detect(text, emoji_regex)) %>% 
  mutate(text = str_remove_all(text, "\\w")) %>% 
  unnest_characters(text, text) %>% 
  count(text, sort = TRUE) %>% 
  slice_max(n, n = 25, with_ties = FALSE) %>% 
  mutate(
    n_occurrences = formattable::color_bar("#99c794", formattable::proportion)(n)
  )
```


Sidebar {.sidebar data-width=200}
=====================================

```{r, echo=FALSE, results='asis'}
htmltools::includeHTML('../fragments/sidebar.html')
```

Home
=====================================

Row
-------------------------------------

### #rstats Tweets

```{r}
valueBox(n_tweets, icon = "fa-comments")
```

### #rstats Retweets

```{r}
valueBox(n_retweets, icon = "fa-retweet")
```

### Users

```{r}
valueBox(n_users, icon = "fa-user")
```

### Likes

```{r}
valueBox(n_likes, icon = "fa-heart")
```

Row
-----------------------------------------------------------------------

### Timeline of Tweets | <small> Jun 2020 - Jun 2021 </small>

```{r}
week_lvs <- c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
myear_lvs <- unique(by_day_metrics$myear)

by_day_metrics %>%
  mutate(weekday = factor(weekday, levels = week_lvs, ordered = FALSE),
         myear = factor(myear, levels = myear_lvs, ordered = FALSE)) %>%
  group_by(myear, weekday) %>%
  summarise(
    tweets = sum(tweets),
    likes = sum(likes),
    retweets = sum(retweets),
  ) %>%
  ungroup() %>%
  group_by(myear) %>%
  e_charts(weekday, timeline = TRUE) %>%
  e_area(tweets, name = "Number of Tweets", stack = "grp") %>%
  e_area(retweets, name = "Number of Retweets", stack = "grp") %>%
  e_area(likes, name = "Number of Likes", stack = "grp") %>%
  e_tooltip(trigger = "axis") %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(
      show = FALSE,
      lineStyle = list(
        color = "#999999",
        width = 0.75,
        type = "dotted"
      )
    )
  ) %>%
  e_x_axis(
    splitArea = list(show = TRUE),
    splitLine = list(show = TRUE),
    axisLabel = list(rotate = 30, interval = 0)
  ) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_color(mycolor)
```


Row {data-height=400}
-----------------------------------------------------------------------

### Tweets Per Month

```{r}
tweets_timeline %>%
  e_charts(time) %>%
  e_bar(n, legend = FALSE) %>%
  e_title(
    text = "Tweets",
    sublink = "#",
    left = "left",
    top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(
      show = FALSE,
      lineStyle = list(
        color = "#999999",
        width = 0.75,
        type = "dotted"
      )
    )
  ) %>%
  e_x_axis(
    splitArea = list(show = TRUE),
    splitLine = list(show = TRUE),
    axisLabel = list(rotate = 30, interval = 0)
  ) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(
    trigger = "axis",
    formatter = htmlwidgets::JS(
      "
    function(params) {
      let date = params[0].value[0]
      let num = `${params[0].value[1]} Tweets`
      return(`${date}</br><b>${num}</b>`);
    }"
    )
  ) %>%
  e_color(mycolor)
```

### Retweets per Month

```{r}
retweets_timeline %>%
  e_charts(time) %>%
  e_bar(n, legend = FALSE) %>%
  e_title(
    text = "Retweets",
    sublink = "#",
    left = "left",
    top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(
      show = FALSE,
      lineStyle = list(
        color = "#999999",
        width = 0.75,
        type = "dotted"
      )
    )
  ) %>%
  e_x_axis(
    splitArea = list(show = TRUE),
    splitLine = list(show = TRUE),
    axisLabel = list(rotate = 30, interval = 0)
  ) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(
    trigger = "axis",
    formatter = htmlwidgets::JS(
      "
    function(params) {
      let date = params[0].value[0]
      let num = `${params[0].value[1]} Retweets`
      return(`${date}</br><b>${num}</b>`);
    }"
    )
  ) %>%
  e_color(mycolor)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Likes per Month

```{r}
likes_timeline %>%
  e_charts(time) %>%
  e_bar(n, legend = FALSE) %>%
  e_title(
    text = "Likes",
    sublink = "#",
    left = "left",
    top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(
      show = FALSE,
      lineStyle = list(
        color = "#999999",
        width = 0.75,
        type = "dotted"
      )
    )
  ) %>%
  e_x_axis(
    splitArea = list(show = TRUE),
    splitLine = list(show = TRUE),
    axisLabel = list(rotate = 30, interval = 0)
  ) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(
    trigger = "axis",
    formatter = htmlwidgets::JS(
      "
    function(params) {
      let date = params[0].value[0]
      let num = `${params[0].value[1]} Likes`
      return(`${date}</br><b>${num}</b>`);
    }"
    )
  ) %>%
  e_color(mycolor) 
```

### Wordcloud of Tweets

```{r}
top_words %>% 
  filter(nchar(word) >= 4) %>% 
  e_color_range(n, color) %>% 
  e_charts() %>% 
  e_cloud(word, n, color, shape = "circle")
```

Row
-----------------------------------------------------------------------

### Popular Hashtags

```{r}
top_hashtags %>%
  e_chart(hashtags) %>%
  e_bar(n, legend = FALSE) %>%
  e_title(
    text = "Top 50 Hashtags",
    sublink = "#",
    left = "left",
    top = 4
  ) %>% 
  e_x_axis(axisLabel = list(rotate = 45, interval = 0)) %>%
  e_axis_labels(y = "Number of occurrences")
```

Row
-----------------------------------------------------------------------

### Most Popular Emojis

```{r}
top_emojis %>% 
  select(text, n_occurrences) %>% 
  knitr::kable(
    format = "html",
    escape = FALSE,
    align = "cl",
    col.names = c("Emoji", "# of occurrences"),
    table.attr = 'class = "table"'
  )
```

### Most Active Users

```{r}
active_users %>%
  knitr::kable(
    format = "html",
    escape = FALSE,
    align = "ll",
    col.names = c("User", "# of tweets"),
    table.attr = 'class = "table"'
  )
```

Row
-----------------------------------------------------------------------

### 10 Most Popular Tweets {.tweet-wall}

Popularity = `Number of Likes + Number of RT * 2`

```{r}
top_tweets_html <- pmap_chr(list(top_tweets$screen_name, top_tweets$status_id, top_tweets$popularity), get_tweet_embed)

HTML(str_glue("{top_tweets_html}"))
```

